### ISSUE TITLE
grunt/gulp tasks の開発方針について

### ISSUE THREAD

**Issue by DriftwoodJP** [megumiteam/iemoto#81]
megumiteam のみなさま

iemoto を便利に利用させて頂いております。
ありがとうございます。

iemoto の grunt/gulp タスクについて、今後の開発の方向性は何か決まっていますでしょうか？

現在のタスクは絞り込んでいるように見えるので、テンプレートとしては提供しない方針なのかなと推測しています。
grunt/gulp を外す選択肢もあり得るのかなと。

例えば現状であれば sass-lint を入れてはどうかなと思うのですが、Fork 利用前提であれば PR しない方が良さそうですし。
https://github.com/DriftwoodJP/iemoto/tree/feature/sass-lint

よろしくお願いします。

**Comment by gatespace** [comment]
_s 自体が Grunt/gulp といったタスクランナーを採用しない方針です。
https://github.com/Automattic/_s/issues/585
_sとの乖離を防ぐため iemoto もそれに準拠します。

iemotoは
- アクションフックの追加
- add_editor_style() のサポート
- デバッグモードでの css 切り替え

がメインでタスクランナーについては最低限のsassのコンパイルを主目的としているためこれ以上の機能追加の予定はありません。
また Grunt/gulp でと同等の機能提供が担保されない場合も実装できません。
その場合はiemotoからフォークして利用されることをおすすめします。

**Comment by DriftwoodJP** [comment]
解決しました。
ありがとうございました。:smile:
